<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="EPINHYDW0F89" failures="2" tests="9" name="com.epam.test.TestOne" time="0.057" errors="1" timestamp="2 Jul 2024 06:06:36 GMT">
  <testcase classname="com.epam.test.TestOne" name="testAddition" time="0.016"/>
  <testcase classname="com.epam.test.TestOne" name="testDivide" time="0.015"/>
  <testcase classname="com.epam.test.TestOne" name="testAdd" time="0.016"/>
  <testcase classname="com.epam.test.TestOne" name="testSquareRootWithNegativeVal" time="0.002">
    <failure message="
Expected exception java.lang.IllegalArgumentException but got org.testng.TestException: 
Expected exception java.lang.IllegalArgumentException but got java.lang.AssertionError: expected [NaN] but found [-7]" type="org.testng.TestException">
      <![CDATA[org.testng.TestException: 
Expected exception java.lang.IllegalArgumentException but got org.testng.TestException: 
Expected exception java.lang.IllegalArgumentException but got java.lang.AssertionError: expected [NaN] but found [-7]
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1497)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1245)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: org.testng.TestException: 
Expected exception java.lang.IllegalArgumentException but got java.lang.AssertionError: expected [NaN] but found [-7]
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1497)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:754)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	... 5 more
Caused by: java.lang.AssertionError: expected [NaN] but found [-7]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at com.epam.test.TestOne.testSquareRootWithNegativeVal(TestOne.java:145)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	... 7 more
]]>
    </failure>
  </testcase> <!-- testSquareRootWithNegativeVal -->
  <testcase classname="com.epam.test.TestOne" name="testSquareRoot" time="0.001"/>
  <testcase classname="com.epam.test.TestOne" name="testSubtract" time="0.001"/>
  <testcase classname="com.epam.test.TestOne" name="testMultiply" time="0.001"/>
  <testcase classname="com.epam.test.TestOne" name="testDivideByZero" time="0.003">
    <failure message="
Expected exception java.lang.IllegalArgumentException but got org.testng.TestException: 
Expected exception java.lang.IllegalArgumentException but got java.lang.ArithmeticException: / by zero" type="org.testng.TestException">
      <![CDATA[org.testng.TestException: 
Expected exception java.lang.IllegalArgumentException but got org.testng.TestException: 
Expected exception java.lang.IllegalArgumentException but got java.lang.ArithmeticException: / by zero
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1497)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1245)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: org.testng.TestException: 
Expected exception java.lang.IllegalArgumentException but got java.lang.ArithmeticException: / by zero
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1497)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:754)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	... 5 more
Caused by: java.lang.ArithmeticException: / by zero
	at com.epam.test.TestOne.testDivideByZero(TestOne.java:123)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	... 7 more
]]>
    </failure>
  </testcase> <!-- testDivideByZero -->
  <testcase classname="com.epam.test.TestOne" name="testAddition" time="0.002">
    <error message="Addition failed expected [6] but found [14]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Addition failed expected [6] but found [14]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:370)
	at com.epam.test.TestOne.testAddition(TestOne.java:63)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)
]]>
    </error>
  </testcase> <!-- testAddition -->
</testsuite> <!-- com.epam.test.TestOne -->
