<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="EPINHYDW0F89" failures="3" tests="9" name="Test Basic One" time="0.452" errors="0" timestamp="2 Jul 2024 06:06:36 GMT">
  <testcase classname="com.epam.test.TestOne" name="testDivide" time="0.015"/>
  <testcase classname="com.epam.test.TestOne" name="testAdd" time="0.016"/>
  <testcase classname="com.epam.test.TestOne" name="testAddition" time="0.016"/>
  <testcase classname="com.epam.test.TestOne" name="testDivideByZero" time="0.002">
    <failure type="org.testng.TestException" message="
Expected exception java.lang.IllegalArgumentException but got org.testng.TestException: 
Expected exception java.lang.IllegalArgumentException but got java.lang.ArithmeticException: / by zero">
      <![CDATA[org.testng.TestException: 
Expected exception java.lang.IllegalArgumentException but got java.lang.ArithmeticException: / by zero
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)
Expected exception java.lang.IllegalArgumentException but got java.lang.ArithmeticException: / by zero
	... 5 more
Caused by: java.lang.ArithmeticException: / by zero
	at com.epam.test.TestOne.testDivideByZero(TestOne.java:123)
	... 7 more
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- testDivideByZero -->
  <testcase classname="com.epam.test.TestOne" name="testMultiply" time="0.001"/>
  <testcase classname="com.epam.test.TestOne" name="testAddition" time="0.002">
    <failure type="java.lang.AssertionError" message="Addition failed expected [6] but found [14]">
      <![CDATA[java.lang.AssertionError: Addition failed expected [6] but found [14]
	at com.epam.test.TestOne.testAddition(TestOne.java:63)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- testAddition -->
  <testcase classname="com.epam.test.TestOne" name="testSquareRoot" time="0.0"/>
  <testcase classname="com.epam.test.TestOne" name="testSubtract" time="0.001"/>
  <testcase classname="com.epam.test.TestOne" name="testSquareRootWithNegativeVal" time="0.002">
    <failure type="org.testng.TestException" message="
Expected exception java.lang.IllegalArgumentException but got org.testng.TestException: 
Expected exception java.lang.IllegalArgumentException but got java.lang.AssertionError: expected [NaN] but found [-7]">
      <![CDATA[org.testng.TestException: 
Expected exception java.lang.IllegalArgumentException but got java.lang.AssertionError: expected [NaN] but found [-7]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)
Expected exception java.lang.IllegalArgumentException but got java.lang.AssertionError: expected [NaN] but found [-7]
	... 5 more
Caused by: java.lang.AssertionError: expected [NaN] but found [-7]
	at com.epam.test.TestOne.testSquareRootWithNegativeVal(TestOne.java:145)
	... 7 more
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- testSquareRootWithNegativeVal -->
</testsuite> <!-- Test Basic One -->
